Repository SinithH/SurfPal, pull requests merged in 2024-03, with the labels that each got.

#39 SDGP-66- Structure the backend API and client Navigation
  client/.env
  client/entrypoints/background.ts
  client/entrypoints/content.ts
  client/entrypoints/sidepanel/App.tsx
  client/entrypoints/sidepanel/components/Navigation/Navigation.tsx
  client/entrypoints/sidepanel/components/Navigation/NavigationLink.tsx
  client/entrypoints/sidepanel/components/Summarization/Summarization.tsx
  client/entrypoints/sidepanel/components/shared/Footer.tsx
  client/entrypoints/sidepanel/components/shared/NavigationLink.tsx
  client/entrypoints/sidepanel/context/navigation-store.ts
  client/entrypoints/sidepanel/services/navigation-service/getNavigation.ts
  client/entrypoints/sidepanel/services/summarization-service/getSummary.ts
  server/navigation-assistant-service/scrape.py
Labels: enhancement

#38 Sdgp 70 landing page improvements
  package-lock.json
  package.json
  surfpal-web/app/layout.tsx
  surfpal-web/app/shared/components/footer.tsx
  surfpal-web/app/shared/components/hero.tsx
  surfpal-web/app/shared/components/mainFeature.tsx
  surfpal-web/app/shared/components/video.tsx
  surfpal-web/package-lock.json
  surfpal-web/package.json
  surfpal-web/public/assets/icons/image1.png
  surfpal-web/public/assets/icons/image10.png
  surfpal-web/public/assets/icons/image11.png
  surfpal-web/public/assets/icons/image12.png
  surfpal-web/public/assets/icons/image13.png
  surfpal-web/public/assets/icons/image14.png
  surfpal-web/public/assets/icons/image15.png
  surfpal-web/public/assets/icons/image16.png
  surfpal-web/public/assets/icons/image17.png
  surfpal-web/public/assets/icons/image18.png
  surfpal-web/public/assets/icons/image2.jpg
  surfpal-web/public/assets/icons/image20.png
  surfpal-web/public/assets/icons/image21.png
  surfpal-web/public/assets/icons/image22.png
  surfpal-web/public/assets/icons/image23.png
  surfpal-web/public/assets/icons/image24.png
  surfpal-web/public/assets/icons/image3.jpg
  surfpal-web/public/assets/icons/image3.png
  surfpal-web/public/assets/icons/image4.jpg
  surfpal-web/public/assets/icons/image4.png
  surfpal-web/public/assets/icons/image5.jpg
  surfpal-web/public/assets/icons/image7.png
Labels: enhancement

#41 SDGP-73- Adding the Search functionality to Navigation
  client/entrypoints/background.ts
  client/entrypoints/content.ts
  client/entrypoints/sidepanel/components/Navigation/Navigation.tsx
  client/entrypoints/sidepanel/components/Navigation/NavigationLink.tsx
  client/entrypoints/sidepanel/components/Navigation/NavigationLinks.tsx
  client/entrypoints/sidepanel/components/Navigation/NavigationLoading.tsx
  client/entrypoints/sidepanel/components/Navigation/NavigationSearch.tsx
  client/entrypoints/sidepanel/components/Summarization/Summarization.tsx
  client/entrypoints/sidepanel/services/navigation-service/getNavigation.ts
  client/enum/purpose-enum.ts
Labels: enhancement

#46 SDGP-75- Added the keyboard functionality to navigation
  .gitignore
  client/entrypoints/content.ts
  client/entrypoints/sidepanel/App.tsx
  client/entrypoints/sidepanel/components/Navigation/Navigation.tsx
  client/entrypoints/sidepanel/components/Navigation/NavigationLink.tsx
  client/entrypoints/sidepanel/components/Navigation/NavigationLinks.tsx
  client/enum/purpose-enum.ts
  server/navigation-assistant-service/connect-with-gemini-ai.py
Labels: enhancement

#47 img recognition service
  .github/workflows/build.client.yml
  client/.env
  client/entrypoints/background.ts
  client/entrypoints/sidepanel/App.tsx
  client/entrypoints/sidepanel/components/ImageRecognition/ImageRecognition.tsx
  client/entrypoints/sidepanel/components/Summarization/Summarization.tsx
  client/entrypoints/sidepanel/services/image-service/getDescription.ts
Labels: feature

#58 SDGP-79- Added generating the top 10 navigation links functionality
  client/entrypoints/sidepanel/App.tsx
  client/entrypoints/sidepanel/components/Navigation/Navigation.tsx
  client/entrypoints/sidepanel/components/Navigation/NavigationLinkWithDescription.tsx
  client/entrypoints/sidepanel/components/Navigation/NavigationLinks.tsx
  client/entrypoints/sidepanel/components/Navigation/NavigationSearch.tsx
  client/entrypoints/sidepanel/components/shared/Footer.tsx
  client/entrypoints/sidepanel/context/navigation-store.ts
  client/entrypoints/sidepanel/services/navigation-service/getNavigation.ts
  client/entrypoints/sidepanel/services/navigation-service/getNavigationTopList.ts
  client/interfaces/navigation-resopnse.interface.ts
  client/interfaces/top-10-navigation-response.interface.ts
Labels: enhancement

#71 SDGP-83- Fixed adding clearing function for onMessage listener
  client/entrypoints/sidepanel/App.tsx
Labels: bug
